/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/Agenti": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["Agente"][];
                        "application/json": components["schemas"]["Agente"][];
                        "text/json": components["schemas"]["Agente"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["AgenteCreateDto"];
                    "text/json": components["schemas"]["AgenteCreateDto"];
                    "application/*+json": components["schemas"]["AgenteCreateDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["Agente"];
                        "application/json": components["schemas"]["Agente"];
                        "text/json": components["schemas"]["Agente"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Agenti/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["Agente"];
                        "application/json": components["schemas"]["Agente"];
                        "text/json": components["schemas"]["Agente"];
                    };
                };
            };
        };
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["AgenteUpdateDto"];
                    "text/json": components["schemas"]["AgenteUpdateDto"];
                    "application/*+json": components["schemas"]["AgenteUpdateDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["LoginDto"];
                    "text/json": components["schemas"]["LoginDto"];
                    "application/*+json": components["schemas"]["LoginDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/AziendaClienti": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["AziendaCliente"][];
                        "application/json": components["schemas"]["AziendaCliente"][];
                        "text/json": components["schemas"]["AziendaCliente"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["AziendaClienteCreateDto"];
                    "text/json": components["schemas"]["AziendaClienteCreateDto"];
                    "application/*+json": components["schemas"]["AziendaClienteCreateDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["AziendaCliente"];
                        "application/json": components["schemas"]["AziendaCliente"];
                        "text/json": components["schemas"]["AziendaCliente"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/AziendaClienti/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["AziendaClienteResponseDto"];
                        "application/json": components["schemas"]["AziendaClienteResponseDto"];
                        "text/json": components["schemas"]["AziendaClienteResponseDto"];
                    };
                };
            };
        };
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["AziendaClienteUpdateDto"];
                    "text/json": components["schemas"]["AziendaClienteUpdateDto"];
                    "application/*+json": components["schemas"]["AziendaClienteUpdateDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Contatti": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    idAziendaCliente?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["Contatto"][];
                        "application/json": components["schemas"]["Contatto"][];
                        "text/json": components["schemas"]["Contatto"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["ContattoCreateDto"];
                    "text/json": components["schemas"]["ContattoCreateDto"];
                    "application/*+json": components["schemas"]["ContattoCreateDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["Contatto"];
                        "application/json": components["schemas"]["Contatto"];
                        "text/json": components["schemas"]["Contatto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Contatti/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ContattoResponseDto"];
                        "application/json": components["schemas"]["ContattoResponseDto"];
                        "text/json": components["schemas"]["ContattoResponseDto"];
                    };
                };
            };
        };
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["ContattoUpdateDto"];
                    "text/json": components["schemas"]["ContattoUpdateDto"];
                    "application/*+json": components["schemas"]["ContattoUpdateDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/LogAttivita": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    idAgente?: number;
                    idOrdine?: number;
                    tipoAttivita?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["LogAttivita"][];
                        "application/json": components["schemas"]["LogAttivita"][];
                        "text/json": components["schemas"]["LogAttivita"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["LogAttivitaCreateDto"];
                    "text/json": components["schemas"]["LogAttivitaCreateDto"];
                    "application/*+json": components["schemas"]["LogAttivitaCreateDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["LogAttivita"];
                        "application/json": components["schemas"]["LogAttivita"];
                        "text/json": components["schemas"]["LogAttivita"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/LogAttivita/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["LogAttivitaResponseDto"];
                        "application/json": components["schemas"]["LogAttivitaResponseDto"];
                        "text/json": components["schemas"]["LogAttivitaResponseDto"];
                    };
                };
            };
        };
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["LogAttivitaUpdateDto"];
                    "text/json": components["schemas"]["LogAttivitaUpdateDto"];
                    "application/*+json": components["schemas"]["LogAttivitaUpdateDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Ordini": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    stato?: string;
                    idAziendaCliente?: number;
                    idAgente?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["Ordine"][];
                        "application/json": components["schemas"]["Ordine"][];
                        "text/json": components["schemas"]["Ordine"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["OrdineCreateDto"];
                    "text/json": components["schemas"]["OrdineCreateDto"];
                    "application/*+json": components["schemas"]["OrdineCreateDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["Ordine"];
                        "application/json": components["schemas"]["Ordine"];
                        "text/json": components["schemas"]["Ordine"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Ordini/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["OrdineResponseDto"];
                        "application/json": components["schemas"]["OrdineResponseDto"];
                        "text/json": components["schemas"]["OrdineResponseDto"];
                    };
                };
            };
        };
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["OrdineUpdateDto"];
                    "text/json": components["schemas"]["OrdineUpdateDto"];
                    "application/*+json": components["schemas"]["OrdineUpdateDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Prodotti": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["Prodotto"][];
                        "application/json": components["schemas"]["Prodotto"][];
                        "text/json": components["schemas"]["Prodotto"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["ProdottoCreateDto"];
                    "text/json": components["schemas"]["ProdottoCreateDto"];
                    "application/*+json": components["schemas"]["ProdottoCreateDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["Prodotto"];
                        "application/json": components["schemas"]["Prodotto"];
                        "text/json": components["schemas"]["Prodotto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Prodotti/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["Prodotto"];
                        "application/json": components["schemas"]["Prodotto"];
                        "text/json": components["schemas"]["Prodotto"];
                    };
                };
            };
        };
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["ProdottoUpdateDto"];
                    "text/json": components["schemas"]["ProdottoUpdateDto"];
                    "application/*+json": components["schemas"]["ProdottoUpdateDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/RigaOrdini": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["RigaOrdine"][];
                        "application/json": components["schemas"]["RigaOrdine"][];
                        "text/json": components["schemas"]["RigaOrdine"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["RigaOrdineCreateDto"];
                    "text/json": components["schemas"]["RigaOrdineCreateDto"];
                    "application/*+json": components["schemas"]["RigaOrdineCreateDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["RigaOrdine"];
                        "application/json": components["schemas"]["RigaOrdine"];
                        "text/json": components["schemas"]["RigaOrdine"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/RigaOrdini/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["RigaOrdine"];
                        "application/json": components["schemas"]["RigaOrdine"];
                        "text/json": components["schemas"]["RigaOrdine"];
                    };
                };
            };
        };
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["RigaOrdineUpdateDto"];
                    "text/json": components["schemas"]["RigaOrdineUpdateDto"];
                    "application/*+json": components["schemas"]["RigaOrdineUpdateDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Utenti": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["UtenteResponseDto"][];
                        "application/json": components["schemas"]["UtenteResponseDto"][];
                        "text/json": components["schemas"]["UtenteResponseDto"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["UtenteCreateDto"];
                    "text/json": components["schemas"]["UtenteCreateDto"];
                    "application/*+json": components["schemas"]["UtenteCreateDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["UtenteResponseDto"];
                        "application/json": components["schemas"]["UtenteResponseDto"];
                        "text/json": components["schemas"]["UtenteResponseDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Utenti/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["UtenteResponseDto"];
                        "application/json": components["schemas"]["UtenteResponseDto"];
                        "text/json": components["schemas"]["UtenteResponseDto"];
                    };
                };
            };
        };
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["UtenteUpdateDto"];
                    "text/json": components["schemas"]["UtenteUpdateDto"];
                    "application/*+json": components["schemas"]["UtenteUpdateDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Agente: {
            /** Format: int32 */
            idAgente?: number;
            nome?: string | null;
            cognome?: string | null;
            email?: string | null;
            telefono?: string | null;
            /** Format: date */
            dataAssunzione?: string;
            attivo?: boolean;
            logAttivita?: components["schemas"]["LogAttivita"][] | null;
            ordini?: components["schemas"]["Ordine"][] | null;
            utente?: components["schemas"]["Utente"];
        };
        AgenteCreateDto: {
            nome: string | null;
            cognome: string | null;
            email: string | null;
            telefono?: string | null;
            /** Format: date */
            dataAssunzione: string;
        };
        AgenteUpdateDto: {
            nome: string | null;
            cognome: string | null;
            email: string | null;
            telefono?: string | null;
            /** Format: date */
            dataAssunzione: string;
            attivo: boolean;
        };
        AziendaCliente: {
            /** Format: int32 */
            idAziendaCliente?: number;
            ragioneSociale?: string | null;
            partitaIva?: string | null;
            codiceFiscale?: string | null;
            indirizzo?: string | null;
            citta?: string | null;
            cap?: string | null;
            provincia?: string | null;
            email?: string | null;
            telefono?: string | null;
            sitoWeb?: string | null;
            note?: string | null;
            attivo?: boolean;
            contatti?: components["schemas"]["Contatto"][] | null;
            ordini?: components["schemas"]["Ordine"][] | null;
        };
        AziendaClienteCreateDto: {
            ragioneSociale: string | null;
            partitaIva: string | null;
            codiceFiscale?: string | null;
            indirizzo?: string | null;
            citta?: string | null;
            cap?: string | null;
            provincia?: string | null;
            email?: string | null;
            telefono?: string | null;
            sitoWeb?: string | null;
            note?: string | null;
        };
        AziendaClienteResponseDto: {
            /** Format: int32 */
            idAziendaCliente?: number;
            ragioneSociale: string | null;
            partitaIva: string | null;
            codiceFiscale?: string | null;
            indirizzo?: string | null;
            citta?: string | null;
            cap?: string | null;
            provincia?: string | null;
            email?: string | null;
            telefono?: string | null;
            sitoWeb?: string | null;
            note?: string | null;
            contatti: components["schemas"]["ContattoResponseDto"][] | null;
        };
        AziendaClienteUpdateDto: {
            ragioneSociale: string | null;
            partitaIva: string | null;
            codiceFiscale?: string | null;
            indirizzo?: string | null;
            citta?: string | null;
            cap?: string | null;
            provincia?: string | null;
            email?: string | null;
            telefono?: string | null;
            sitoWeb?: string | null;
            note?: string | null;
            attivo: boolean;
        };
        Contatto: {
            /** Format: int32 */
            idContatto?: number;
            /** Format: int32 */
            idAziendaCliente?: number;
            nome?: string | null;
            cognome?: string | null;
            ruolo?: string | null;
            email?: string | null;
            telefono?: string | null;
            cellulare?: string | null;
            note?: string | null;
            attivo?: boolean;
            idAziendaClienteNavigation?: components["schemas"]["AziendaCliente"];
            logAttivita?: components["schemas"]["LogAttivita"][] | null;
            ordini?: components["schemas"]["Ordine"][] | null;
        };
        ContattoCreateDto: {
            /** Format: int32 */
            idAziendaCliente: number;
            nome: string | null;
            cognome: string | null;
            ruolo?: string | null;
            email?: string | null;
            telefono?: string | null;
            cellulare?: string | null;
            note?: string | null;
        };
        ContattoResponseDto: {
            /** Format: int32 */
            idContatto?: number;
            /** Format: int32 */
            idAziendaCliente?: number;
            ragioneSocialeAzienda: string | null;
            nome: string | null;
            cognome: string | null;
            ruolo?: string | null;
            email?: string | null;
            telefono?: string | null;
            cellulare?: string | null;
        };
        ContattoUpdateDto: {
            /** Format: int32 */
            idAziendaCliente: number;
            nome: string | null;
            cognome: string | null;
            ruolo?: string | null;
            email?: string | null;
            telefono?: string | null;
            cellulare?: string | null;
            note?: string | null;
            attivo: boolean;
        };
        LogAttivita: {
            /** Format: int32 */
            idLogAttivita?: number;
            /** Format: int32 */
            idOrdine?: number | null;
            /** Format: int32 */
            idContatto?: number | null;
            /** Format: int32 */
            idAgente?: number;
            /** Format: date-time */
            dataOra?: string;
            tipoAttivita?: string | null;
            oggetto?: string | null;
            descrizione?: string | null;
            esito?: string | null;
            allegatoUrl?: string | null;
            idAgenteNavigation?: components["schemas"]["Agente"];
            idContattoNavigation?: components["schemas"]["Contatto"];
            idOrdineNavigation?: components["schemas"]["Ordine"];
        };
        LogAttivitaCreateDto: {
            /** Format: int32 */
            idOrdine?: number | null;
            /** Format: int32 */
            idContatto?: number | null;
            /** Format: int32 */
            idAgente: number;
            tipoAttivita: string | null;
            oggetto?: string | null;
            descrizione?: string | null;
            esito?: string | null;
            allegatoUrl?: string | null;
        };
        LogAttivitaResponseDto: {
            /** Format: int32 */
            idLogAttivita?: number;
            /** Format: int32 */
            idOrdine?: number | null;
            /** Format: int32 */
            idContatto?: number | null;
            nomeContatto?: string | null;
            /** Format: int32 */
            idAgente?: number;
            nomeAgente: string | null;
            /** Format: date-time */
            dataOra?: string;
            tipoAttivita: string | null;
            oggetto?: string | null;
            descrizione?: string | null;
            esito?: string | null;
            allegatoUrl?: string | null;
        };
        LogAttivitaUpdateDto: {
            /** Format: int32 */
            idOrdine?: number | null;
            /** Format: int32 */
            idContatto?: number | null;
            /** Format: int32 */
            idAgente: number;
            tipoAttivita: string | null;
            oggetto?: string | null;
            descrizione?: string | null;
            esito?: string | null;
            allegatoUrl?: string | null;
        };
        LoginDto: {
            email: string | null;
            password: string | null;
        };
        Ordine: {
            /** Format: int32 */
            idOrdine?: number;
            /** Format: int32 */
            idAziendaCliente?: number;
            /** Format: int32 */
            idAgente?: number;
            /** Format: int32 */
            idContattoRiferimento?: number | null;
            /** Format: date-time */
            dataOrdine?: string;
            stato?: string | null;
            note?: string | null;
            idAgenteNavigation?: components["schemas"]["Agente"];
            idAziendaClienteNavigation?: components["schemas"]["AziendaCliente"];
            idContattoRiferimentoNavigation?: components["schemas"]["Contatto"];
            logAttivita?: components["schemas"]["LogAttivita"][] | null;
            rigaOrdini?: components["schemas"]["RigaOrdine"][] | null;
        };
        OrdineCreateDto: {
            /** Format: int32 */
            idAziendaCliente: number;
            /** Format: int32 */
            idAgente: number;
            /** Format: int32 */
            idContattoRiferimento?: number | null;
            note?: string | null;
        };
        OrdineResponseDto: {
            /** Format: int32 */
            idOrdine?: number;
            /** Format: int32 */
            idAziendaCliente?: number;
            ragioneSocialeAzienda: string | null;
            /** Format: int32 */
            idAgente?: number;
            nomeAgente: string | null;
            /** Format: int32 */
            idContattoRiferimento?: number | null;
            nomeContattoRiferimento?: string | null;
            stato: string | null;
            /** Format: date-time */
            dataOrdine?: string;
            rigaOrdini: components["schemas"]["RigaOrdineResponseDto"][] | null;
        };
        OrdineUpdateDto: {
            /** Format: int32 */
            idAziendaCliente: number;
            /** Format: int32 */
            idAgente: number;
            /** Format: int32 */
            idContattoRiferimento?: number | null;
            stato: string | null;
            note?: string | null;
        };
        Prodotto: {
            /** Format: int32 */
            idProdotto?: number;
            nome?: string | null;
            descrizione?: string | null;
            tipo?: string | null;
            codice?: string | null;
            /** Format: double */
            prezzoListino?: number;
            attivo?: boolean;
            rigaOrdini?: components["schemas"]["RigaOrdine"][] | null;
        };
        ProdottoCreateDto: {
            nome: string | null;
            descrizione?: string | null;
            tipo: string | null;
            codice: string | null;
            /** Format: double */
            prezzoListino: number;
        };
        ProdottoUpdateDto: {
            nome: string | null;
            descrizione?: string | null;
            tipo: string | null;
            codice: string | null;
            /** Format: double */
            prezzoListino: number;
            attivo: boolean;
        };
        RigaOrdine: {
            /** Format: int32 */
            idRigaOrdine?: number;
            /** Format: int32 */
            idOrdine?: number;
            /** Format: int32 */
            idProdotto?: number;
            /** Format: int32 */
            quantita?: number;
            /** Format: double */
            prezzoPattuito?: number;
            /** Format: double */
            sconto?: number;
            /** Format: double */
            totaleRiga?: number | null;
            idOrdineNavigation?: components["schemas"]["Ordine"];
            idProdottoNavigation?: components["schemas"]["Prodotto"];
        };
        RigaOrdineCreateDto: {
            /** Format: int32 */
            idOrdine: number;
            /** Format: int32 */
            idProdotto: number;
            /** Format: int32 */
            quantita: number;
            /** Format: double */
            prezzoPattuito: number;
            /** Format: double */
            sconto?: number;
        };
        RigaOrdineResponseDto: {
            /** Format: int32 */
            idRigaOrdine?: number;
            /** Format: int32 */
            idProdotto?: number;
            nomeProdotto: string | null;
            /** Format: double */
            prezzoPattuito?: number;
            /** Format: double */
            sconto?: number;
            /** Format: int32 */
            quantita?: number;
            /** Format: double */
            totaleRiga?: number | null;
        };
        RigaOrdineUpdateDto: {
            /** Format: int32 */
            idOrdine: number;
            /** Format: int32 */
            idProdotto: number;
            /** Format: int32 */
            quantita: number;
            /** Format: double */
            prezzoPattuito: number;
            /** Format: double */
            sconto?: number;
        };
        Utente: {
            /** Format: int32 */
            idUtente?: number;
            email?: string | null;
            passwordHash?: string | null;
            ruolo?: string | null;
            /** Format: int32 */
            idAgente?: number | null;
            attivo?: boolean;
            /** Format: date-time */
            dataCreazione?: string;
            idAgenteNavigation?: components["schemas"]["Agente"];
        };
        UtenteCreateDto: {
            email: string | null;
            password: string | null;
            ruolo: string | null;
            /** Format: int32 */
            idAgente?: number | null;
        };
        UtenteResponseDto: {
            /** Format: int32 */
            idUtente?: number;
            email: string | null;
            ruolo: string | null;
            /** Format: int32 */
            idAgente?: number | null;
            attivo?: boolean;
            /** Format: date-time */
            dataCreazione?: string;
        };
        UtenteUpdateDto: {
            email: string | null;
            ruolo: string | null;
            /** Format: int32 */
            idAgente?: number | null;
            attivo?: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
